name: xiuxianca

on:
  workflow_dispatch:
  schedule:
    - cron: '1 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiuxianca
        env:
          aenr2: ${{ secrets.aenr2 }}
        run: |
          echo $aenr2 | jq -r .gx955 | /bin/bash
          echo $xlma3 | jq -r .ei59239 | /bin/bash
          echo $zgwn0 | jq -r .m594 | /bin/bash
          echo $tzs7 | jq -r .vov78 | /bin/bash

